//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class WalkingChar :MonoBehaviour
{
	public float slowDownHorGround = 0.1f;
	public int maxSpeed = 4;

	//slowdown
	public void ApplySlowdown ()
	{
		rigidbody2D.velocity = new Vector2(rigidbody2D.velocity.x * slowDownHorGround, rigidbody2D.velocity.y);
	}

	// apply max move
	public void ApplyMaxMoveSpeed(){
		if(Mathf.Abs (rigidbody2D.velocity.x)> maxSpeed){
			rigidbody2D.velocity = new Vector2(Mathf.Sign(rigidbody2D.velocity.x) * maxSpeed, rigidbody2D.velocity.y);
		}
	}
}

